exports.movedex = {
1:{name:"Absorb",type:"grass",class:"special"},
2:{name:"Acid",type:"poison",class:"special"},
3:{name:"Acid Armor",type:"poison",class:"status"},
4:{name:"Acid Spray",type:"poison",class:"special"},
5:{name:"Acrobatics",type:"flying",class:"physical",TM:"62"},
6:{name:"Acupressure",type:"normal",class:"status"},
7:{name:"Aerial Ace",type:"flying",class:"physical",TM:"40"},
8:{name:"Aeroblast",type:"flying",class:"special"},
9:{name:"After You",type:"normal",class:"status"},
10:{name:"Agility",type:"psychic",class:"status"},
11:{name:"Air Cutter",type:"flying",class:"special"},
12:{name:"Air Slash",type:"flying",class:"special"},
13:{name:"Ally Switch",type:"psychic",class:"status"},
14:{name:"Amnesia",type:"psychic",class:"status"},
15:{name:"Ancient Power",type:"rock",class:"special"},
16:{name:"Aqua Jet",type:"water",class:"physical"},
17:{name:"Aqua Ring",type:"water",class:"status"},
18:{name:"Aqua Tail",type:"water",class:"physical"},
19:{name:"Arm Thrust",type:"fighting",class:"physical"},
20:{name:"Aromatherapy",type:"grass",class:"status"},
21:{name:"Aromatic Mist",type:"fairy",class:"status"},
22:{name:"Assist",type:"normal",class:"status"},
23:{name:"Assurance",type:"dark",class:"physical"},
24:{name:"Astonish",type:"ghost",class:"physical"},
25:{name:"Attack Order",type:"bug",class:"physical"},
26:{name:"Attract",type:"normal",class:"status",TM:"45"},
27:{name:"Aura Sphere",type:"fighting",class:"special"},
28:{name:"Aurora Beam",type:"ice",class:"special"},
29:{name:"Autotomize",type:"steel",class:"status"},
30:{name:"Avalanche",type:"ice",class:"physical"},
31:{name:"Baby-Doll Eyes",type:"fairy",class:"status"},
32:{name:"Barrage",type:"normal",class:"physical"},
33:{name:"Barrier",type:"psychic",class:"status"},
34:{name:"Baton Pass",type:"normal",class:"status"},
35:{name:"Beat Up",type:"dark",class:"physical"},
36:{name:"Belch",type:"poison",class:"special"},
37:{name:"Belly Drum",type:"normal",class:"status"},
38:{name:"Bestow",type:"normal",class:"status"},
39:{name:"Bide",type:"normal",class:"physical"},
40:{name:"Bind",type:"normal",class:"physical"},
41:{name:"Bite",type:"dark",class:"physical"},
42:{name:"Blast Burn",type:"fire",class:"special"},
43:{name:"Blaze Kick",type:"fire",class:"physical"},
44:{name:"Blizzard",type:"ice",class:"special", TM:"14"},
45:{name:"Block",type:"normal",class:"status"},
46:{name:"Blue Flare",type:"fire",class:"special"},
47:{name:"Body Slam",type:"normal",class:"physical"},
48:{name:"Bolt Strike",type:"electric",class:"physical"},
49:{name:"Bone Club",type:"ground",class:"physical"},
50:{name:"Bone Rush",type:"ground",class:"physical"},
51:{name:"Bonemerang",type:"ground",class:"physical"},
52:{name:"Boomburst",type:"normal",class:"special"},
53:{name:"Bounce",type:"flying",class:"physical"},
54:{name:"Brave Bird",type:"flying",class:"physical"},
55:{name:"Brick Break",type:"fighting",class:"physical",TM:"31"},
56:{name:"Brine",type:"water",class:"special"},
57:{name:"Bubble",type:"water",class:"special"},
58:{name:"Bubble Beam",type:"water",class:"special"},
59:{name:"Bug Bite",type:"bug",class:"physical"},
60:{name:"Bug Buzz",type:"bug",class:"special"},
61:{name:"Bulk Up",type:"fighting",class:"status",TM:"08"},
62:{name:"Bulldoze",type:"ground",class:"physical",TM:"78"},
63:{name:"Bullet Punch",type:"steel",class:"physical"},
64:{name:"Bullet Seed",type:"grass",class:"physical"},
65:{name:"Calm Mind",type:"psychic",class:"status",TM:"04"},
66:{name:"Camouflage",type:"normal",class:"status"},
67:{name:"Captivate",type:"normal",class:"status"},
68:{name:"Celebrate",type:"normal",class:"status"},
69:{name:"Charge",type:"electric",class:"status"},
70:{name:"Charge Beam",type:"electric",class:"special",TM:"57"},
71:{name:"Charm",type:"fairy",class:"status"},
72:{name:"Chatter",type:"flying",class:"special"},
73:{name:"Chip Away",type:"normal",class:"physical"},
74:{name:"Circle Throw",type:"fighting",class:"physical"},
75:{name:"Clamp",type:"water",class:"physical"},
76:{name:"Clear Smog",type:"poison",class:"special"},
77:{name:"Close Combat",type:"fighting",class:"physical"},
78:{name:"Coil",type:"poison",class:"status"},
79:{name:"Comet Punch",type:"normal",class:"physical"},
80:{name:"Confide",type:"normal",class:"status",TM:"100"},
81:{name:"Confuse Ray",type:"ghost",class:"status"},
82:{name:"Confusion",type:"psychic",class:"special"},
83:{name:"Constrict",type:"normal",class:"physical"},
84:{name:"Conversion",type:"normal",class:"status"},
85:{name:"Conversion 2",type:"normal",class:"status"},
86:{name:"Copycat",type:"normal",class:"status"},
87:{name:"Cosmic Power",type:"psychic",class:"status"},
88:{name:"Cotton Guard",type:"grass",class:"status"},
89:{name:"Cotton Spore",type:"grass",class:"status"},
90:{name:"Counter",type:"fighting",class:"physical"},
91:{name:"Covet",type:"normal",class:"physical"},
92:{name:"Crabhammer",type:"water",class:"physical"},
93:{name:"Crafty Shield",type:"fairy",class:"status"},
94:{name:"Cross Chop",type:"fighting",class:"physical"},
95:{name:"Cross Poison",type:"poison",class:"physical"},
96:{name:"Crunch",type:"dark",class:"physical"},
97:{name:"Crush Claw",type:"normal",class:"physical"},
98:{name:"Crush Grip",type:"normal",class:"physical"},
99:{name:"Curse",type:"ghost",class:"status"},
100:{name:"Cut",type:"normal",class:"physical",TM:"HM01"},
101:{name:"Dark Pulse",type:"dark",class:"special",TM:"97"},
102:{name:"Dark Void",type:"dark",class:"status"},
103:{name:"Dazzling Gleam",type:"fairy",class:"special",TM:"99"},
104:{name:"Defend Order",type:"bug",class:"status"},
105:{name:"Defense Curl",type:"normal",class:"status"},
106:{name:"Defog",type:"flying",class:"status"},
107:{name:"Destiny Bond",type:"ghost",class:"status"},
108:{name:"Detect",type:"fighting",class:"status"},
109:{name:"Diamond Storm",type:"rock",class:"physical"},
110:{name:"Dig",type:"ground",class:"physical",TM:"28"},
111:{name:"Disable",type:"normal",class:"status"},
112:{name:"Disarming Voice",type:"fairy",class:"special"},
113:{name:"Discharge",type:"electric",class:"special"},
114:{name:"Dive",type:"water",class:"physical"},
115:{name:"Dizzy Punch",type:"normal",class:"physical"},
116:{name:"Doom Desire",type:"steel",class:"special"},
117:{name:"Double Hit",type:"normal",class:"physical"},
118:{name:"Double Kick",type:"fighting",class:"physical"},
119:{name:"Double Slap",type:"normal",class:"physical"},
120:{name:"Double Team",type:"normal",class:"status",TM:"32"},
121:{name:"Double-Edge",type:"normal",class:"physical"},
122:{name:"Draco Meteor",type:"dragon",class:"special"},
123:{name:"Dragon Breath",type:"dragon",class:"special"},
124:{name:"Dragon Claw",type:"dragon",class:"physical",TM:"02"},
125:{name:"Dragon Dance",type:"dragon",class:"status"},
126:{name:"Dragon Pulse",type:"dragon",class:"special"},
127:{name:"Dragon Rage",type:"dragon",class:"special"},
128:{name:"Dragon Rush",type:"dragon",class:"physical"},
129:{name:"Dragon Tail",type:"dragon",class:"physical",TM:"82"},
130:{name:"Drain Punch",type:"fighting",class:"physical"},
131:{name:"Draining Kiss",type:"fairy",class:"special"},
132:{name:"Dream Eater",type:"psychic",class:"special",TM:"85"},
133:{name:"Drill Peck",type:"flying",class:"physical"},
134:{name:"Drill Run",type:"ground",class:"physical"},
135:{name:"Dual Chop",type:"dragon",class:"physical"},
136:{name:"Dynamic Punch",type:"fighting",class:"physical"},
137:{name:"Earth Power",type:"ground",class:"special"},
138:{name:"Earthquake",type:"ground",class:"physical",TM:"26"},
139:{name:"Echoed Voice",type:"normal",class:"special",TM:"49"},
140:{name:"Eerie Impulse",type:"electric",class:"status"},
141:{name:"Egg Bomb",type:"normal",class:"physical"},
142:{name:"Electric Terrain",type:"electric",class:"status"},
143:{name:"Electrify",type:"electric",class:"status"},
144:{name:"Electro Ball",type:"electric",class:"special"},
145:{name:"Electroweb",type:"electric",class:"special"},
146:{name:"Embargo",type:"dark",class:"status",TM:"63"},
147:{name:"Ember",type:"fire",class:"special"},
148:{name:"Encore",type:"normal",class:"status"},
149:{name:"Endeavor",type:"normal",class:"physical"},
150:{name:"Endure",type:"normal",class:"status"},
151:{name:"Energy Ball",type:"grass",class:"special",TM:"53"},
152:{name:"Entrainment",type:"normal",class:"status"},
153:{name:"Eruption",type:"fire",class:"special"},
154:{name:"Explosion",type:"normal",class:"physical", TM:"64"},
155:{name:"Extrasensory",type:"psychic",class:"special"},
156:{name:"Extreme Speed",type:"normal",class:"physical"},
157:{name:"Facade",type:"normal",class:"physical",TM:"42"},
158:{name:"Fairy Lock",type:"fairy",class:"status"},
159:{name:"Fairy Wind",type:"fairy",class:"special"},
160:{name:"Fake Out",type:"normal",class:"physical"},
161:{name:"Fake Tears",type:"dark",class:"status"},
162:{name:"False Swipe",type:"normal",class:"physical",TM:"54"},
163:{name:"Feather Dance",type:"flying",class:"status"},
164:{name:"Feint",type:"normal",class:"physical"},
165:{name:"Feint Attack",type:"dark",class:"physical"},
166:{name:"Fell Stinger",type:"bug",class:"physical"},
167:{name:"Fiery Dance",type:"fire",class:"special"},
168:{name:"Final Gambit",type:"fighting",class:"special"},
169:{name:"Fire Blast",type:"fire",class:"special", TM:"38"},
170:{name:"Fire Fang",type:"fire",class:"physical"},
171:{name:"Fire Pledge",type:"fire",class:"special"},
172:{name:"Fire Punch",type:"fire",class:"physical"},
173:{name:"Fire Spin",type:"fire",class:"special"},
174:{name:"Fissure",type:"ground",class:"physical"},
175:{name:"Flail",type:"normal",class:"physical"},
176:{name:"Flame Burst",type:"fire",class:"special"},
177:{name:"Flame Charge",type:"fire",class:"physical",TM:"43"},
178:{name:"Flame Wheel",type:"fire",class:"physical"},
179:{name:"Flamethrower",type:"fire",class:"special",TM:"35"},
180:{name:"Flare Blitz",type:"fire",class:"physical"},
181:{name:"Flash",type:"normal",class:"status",TM:"70"},
182:{name:"Flash Cannon",type:"steel",class:"special",TM:"91"},
183:{name:"Flatter",type:"dark",class:"status"},
184:{name:"Fling",type:"dark",class:"physical",TM:"56"},
185:{name:"Flower Shield",type:"fairy",class:"status"},
186:{name:"Fly",type:"flying",class:"physical",TM:"HM02"},
187:{name:"Flying Press",type:"fighting",class:"physical"},
188:{name:"Focus Blast",type:"fighting",class:"special", TM:"52"},
189:{name:"Focus Energy",type:"normal",class:"status"},
190:{name:"Focus Punch",type:"fighting",class:"physical"},
191:{name:"Follow Me",type:"normal",class:"status"},
192:{name:"Force Palm",type:"fighting",class:"physical"},
193:{name:"Foresight",type:"normal",class:"status"},
194:{name:"Forest's Curse",type:"grass",class:"status"},
195:{name:"Foul Play",type:"dark",class:"physical"},
196:{name:"Freeze Shock",type:"ice",class:"physical"},
197:{name:"Freeze-Dry",type:"ice",class:"special"},
198:{name:"Frenzy Plant",type:"grass",class:"special"},
199:{name:"Frost Breath",type:"ice",class:"special",TM:"79"},
200:{name:"Frustration",type:"normal",class:"physical",TM:"21"},
201:{name:"Fury Attack",type:"normal",class:"physical"},
200:{name:":Fury Cutter",type:"bug",class:"physical"},
202:{name:"Fury Swipes",type:"normal",class:"physical"},
203:{name:"Fusion Bolt",type:"electric",class:"physical"},
204:{name:"Fusion Flare",type:"fire",class:"special"},
205:{name:"Future Sight",type:"psychic",class:"special"},
206:{name:"Gastro Acid",type:"poison",class:"status"},
207:{name:"Gear Grind",type:"steel",class:"physical"},
208:{name:"Geomancy",type:"fairy",class:"status"},
209:{name:"Giga Drain",type:"grass",class:"special"},
210:{name:"Giga Impact",type:"normal",class:"physical", TM:"68"},
211:{name:"Glaciate",type:"ice",class:"special"},
212:{name:"Glare",type:"normal",class:"status"},
213:{name:"Grass Knot",type:"grass",class:"special",TM:"86"},
214:{name:"Grass Pledge",type:"grass",class:"special"},
215:{name:"Grass Whistle",type:"grass",class:"status"},
216:{name:"Grassy Terrain",type:"grass",class:"status"},
217:{name:"Gravity",type:"psychic",class:"status"},
218:{name:"Growl",type:"normal",class:"status"},
219:{name:"Growth",type:"normal",class:"status"},
220:{name:"Grudge",type:"ghost",class:"status"},
221:{name:"Guard Split",type:"psychic",class:"status"},
222:{name:"Guard Swap",type:"psychic",class:"status"},
223:{name:"Guillotine",type:"normal",class:"physical"},
224:{name:"Gunk Shot",type:"poison",class:"physical"},
225:{name:"Gust",type:"flying",class:"special"},
226:{name:"Gyro Ball",type:"steel",class:"physical", TM:"74"},
227:{name:"Hail",type:"ice",class:"status",TM:"07"},
228:{name:"Hammer Arm",type:"fighting",class:"physical"},
229:{name:"Happy Hour",type:"normal",class:"status"},
230:{name:"Harden",type:"normal",class:"status"},
231:{name:"Haze",type:"ice",class:"status"},
232:{name:"Head Charge",type:"normal",class:"physical"},
233:{name:"Head Smash",type:"rock",class:"physical"},
234:{name:"Headbutt",type:"normal",class:"physical"},
235:{name:"Heal Bell",type:"normal",class:"status"},
236:{name:"Heal Block",type:"psychic",class:"status"},
237:{name:"Heal Order",type:"bug",class:"status"},
238:{name:"Heal Pulse",type:"psychic",class:"status"},
239:{name:"Healing Wish",type:"psychic",class:"status"},
240:{name:"Heart Stamp",type:"psychic",class:"physical"},
241:{name:"Heart Swap",type:"psychic",class:"status"},
242:{name:"Heat Crash",type:"fire",class:"physical"},
243:{name:"Heat Wave",type:"fire",class:"special"},
244:{name:"Heavy Slam",type:"steel",class:"physical"},
245:{name:"Helping Hand",type:"normal",class:"status"},
246:{name:"Hex",type:"ghost",class:"special"},
247:{name:"Hidden Power",type:"normal",class:"special",TM:"10"},
248:{name:"High Jump Kick",type:"fighting",class:"physical"},
249:{name:"Hold Back",type:"normal",class:"physical"},
250:{name:"Hold Hands",type:"normal",class:"status"},
251:{name:"Hone Claws",type:"dark",class:"status",TM:"01"},
252:{name:"Horn Attack",type:"normal",class:"physical"},
253:{name:"Horn Drill",type:"normal",class:"physical"},
254:{name:"Horn Leech",type:"grass",class:"physical"},
255:{name:"Howl",type:"normal",class:"status"},
256:{name:"Hurricane",type:"flying",class:"special"},
257:{name:"Hydro Cannon",type:"water",class:"special"},
258:{name:"Hydro Pump",type:"water",class:"special"},
259:{name:"Hyper Beam",type:"normal",class:"special", TM:"15"},
260:{name:"Hyper Fang",type:"normal",class:"physical"},
261:{name:"Hyper Voice",type:"normal",class:"special"},
262:{name:"Hyperspace Hole",type:"psychic",class:"special"},
263:{name:"Hypnosis",type:"psychic",class:"status"},
264:{name:"Ice Ball",type:"ice",class:"physical"},
265:{name:"Ice Beam",type:"ice",class:"special",TM:"13"},
266:{name:"Ice Burn",type:"ice",class:"special"},
267:{name:"Ice Fang",type:"ice",class:"physical"},
268:{name:"Ice Punch",type:"ice",class:"physical"},
269:{name:"Ice Shard",type:"ice",class:"physical"},
270:{name:"Icicle Crash",type:"ice",class:"physical"},
271:{name:"Icicle Spear",type:"ice",class:"physical"},
272:{name:"Icy Wind",type:"ice",class:"special"},
273:{name:"Imprison",type:"psychic",class:"status"},
274:{name:"Incinerate",type:"fire",class:"special",TM:"59"},
275:{name:"Inferno",type:"fire",class:"special"},
276:{name:"Infestation",type:"bug",class:"special",TM:"83"},
277:{name:"Ingrain",type:"grass",class:"status"},
278:{name:"Ion Deluge",type:"electric",class:"status"},
279:{name:"Iron Defense",type:"steel",class:"status"},
280:{name:"Iron Head",type:"steel",class:"physical"},
281:{name:"Iron Tail",type:"steel",class:"physical"},
282:{name:"Judgment",type:"normal",class:"special"},
283:{name:"Jump Kick",type:"fighting",class:"physical"},
284:{name:"Karate Chop",type:"fighting",class:"physical"},
285:{name:"Kinesis",type:"psychic",class:"status"},
286:{name:"King's Shield",type:"steel",class:"status"},
287:{name:"Knock Off",type:"dark",class:"physical"},
288:{name:"Land's Wrath",type:"ground",class:"physical"},
289:{name:"Last Resort",type:"normal",class:"physical"},
290:{name:"Lava Plume",type:"fire",class:"special"},
291:{name:"Leaf Blade",type:"grass",class:"physical"},
292:{name:"Leaf Storm",type:"grass",class:"special"},
293:{name:"Leaf Tornado",type:"grass",class:"special"},
294:{name:"Leech Life",type:"bug",class:"physical"},
295:{name:"Leech Seed",type:"grass",class:"status"},
296:{name:"Leer",type:"normal",class:"status"},
297:{name:"Lick",type:"ghost",class:"physical"},
298:{name:"Light Screen",type:"psychic",class:"status",TM:"16"},
299:{name:"Light of Ruin",type:"fairy",class:"special"},
300:{name:"Lock-On",type:"normal",class:"status"},
301:{name:"Lovely Kiss",type:"normal",class:"status"},
302:{name:"Low Kick",type:"fighting",class:"physical"},
303:{name:"Low Sweep",type:"fighting",class:"physical",TM:"47"},
304:{name:"Lucky Chant",type:"normal",class:"status"},
305:{name:"Lunar Dance",type:"psychic",class:"status"},
306:{name:"Luster Purge",type:"psychic",class:"special"},
307:{name:"Mach Punch",type:"fighting",class:"physical"},
308:{name:"Magic Coat",type:"psychic",class:"status"},
309:{name:"Magic Room",type:"psychic",class:"status"},
310:{name:"Magical Leaf",type:"grass",class:"special"},
311:{name:"Magma Storm",type:"fire",class:"special"},
312:{name:"Magnet Bomb",type:"steel",class:"physical"},
313:{name:"Magnet Rise",type:"electric",class:"status"},
314:{name:"Magnetic Flux",type:"electric",class:"status"},
315:{name:"Magnitude",type:"ground",class:"physical"},
316:{name:"Mat Block",type:"fighting",class:"status"},
317:{name:"Me First",type:"normal",class:"status"},
318:{name:"Mean Look",type:"normal",class:"status"},
319:{name:"Meditate",type:"psychic",class:"status"},
320:{name:"Mega Drain",type:"grass",class:"special"},
321:{name:"Mega Kick",type:"normal",class:"physical"},
322:{name:"Mega Punch",type:"normal",class:"physical"},
323:{name:"Megahorn",type:"bug",class:"physical"},
324:{name:"Memento",type:"dark",class:"status"},
325:{name:"Metal Burst",type:"steel",class:"physical"},
326:{name:"Metal Claw",type:"steel",class:"physical"},
327:{name:"Metal Sound",type:"steel",class:"status"},
328:{name:"Meteor Mash",type:"steel",class:"physical"},
329:{name:"Metronome",type:"normal",class:"status"},
330:{name:"Milk Drink",type:"normal",class:"status"},
331:{name:"Mimic",type:"normal",class:"status"},
332:{name:"Mind Reader",type:"normal",class:"status"},
333:{name:"Minimize",type:"normal",class:"status"},
334:{name:"Miracle Eye",type:"psychic",class:"status"},
335:{name:"Mirror Coat",type:"psychic",class:"special"},
336:{name:"Mirror Move",type:"flying",class:"status"},
337:{name:"Mirror Shot",type:"steel",class:"special"},
338:{name:"Mist",type:"ice",class:"status"},
339:{name:"Mist Ball",type:"psychic",class:"special"},
340:{name:"Misty Terrain",type:"fairy",class:"status"},
341:{name:"Moonblast",type:"fairy",class:"special"},
342:{name:"Moonlight",type:"fairy",class:"status"},
343:{name:"Morning Sun",type:"normal",class:"status"},
344:{name:"Mud Bomb",type:"ground",class:"special"},
345:{name:"Mud Shot",type:"ground",class:"special"},
346:{name:"Mud Sport",type:"ground",class:"status"},
347:{name:"Mud-Slap",type:"ground",class:"special"},
348:{name:"Muddy Water",type:"water",class:"special"},
349:{name:"Mystical Fire",type:"fire",class:"special"},
350:{name:"Nasty Plot",type:"dark",class:"status"},
351:{name:"Natural Gift",type:"normal",class:"physical"},
352:{name:"Nature Power",type:"normal",class:"status",TM:"96"},
353:{name:"Needle Arm",type:"grass",class:"physical"},
354:{name:"Night Daze",type:"dark",class:"special"},
355:{name:"Night Shade",type:"ghost",class:"special"},
356:{name:"Night Slash",type:"dark",class:"physical"},
357:{name:"Nightmare",type:"ghost",class:"special"},
358:{name:"Noble Roar",type:"normal",class:"status"},
359:{name:"Nuzzle",type:"electric",class:"physical"},
360:{name:"Oblivion Wing",type:"flying",class:"special"},
361:{name:"Octazooka",type:"water",class:"special"},
362:{name:"Odor Sleuth",type:"normal",class:"status"},
363:{name:"Ominous Wind",type:"ghost",class:"special"},
364:{name:"Outrage",type:"dragon",class:"physical"},
365:{name:"Overheat",type:"fire",class:"special", TM:"50"},
366:{name:"Pain Split",type:"normal",class:"status"},
367:{name:"Parabolic Charge",type:"electric",class:"special"},
368:{name:"Parting Shot",type:"dark",class:"status"},
369:{name:"Pay Day",type:"normal",class:"physical"},
370:{name:"Payback",type:"dark",class:"physical",TM:"66"},
371:{name:"Peck",type:"flying",class:"physical"},
372:{name:"Perish Song",type:"normal",class:"status"},
373:{name:"Petal Blizzard",type:"grass",class:"physical"},
374:{name:"Petal Dance",type:"grass",class:"special"},
375:{name:"Phantom Force",type:"ghost",class:"physical"},
376:{name:"Pin Missile",type:"bug",class:"physical"},
377:{name:"Play Nice",type:"normal",class:"status"},
378:{name:"Play Rough",type:"fairy",class:"physical"},
379:{name:"Pluck",type:"flying",class:"physical"},
380:{name:"Poison Fang",type:"poison",class:"physical"},
381:{name:"Poison Gas",type:"poison",class:"status"},
382:{name:"Poison Jab",type:"poison",class:"physical",TM:"84"},
383:{name:"Poison Powder",type:"poison",class:"status"},
384:{name:"Poison Sting",type:"poison",class:"physical"},
385:{name:"Poison Tail",type:"poison",class:"physical"},
386:{name:"Pound",type:"normal",class:"physical"},
387:{name:"Powder",type:"bug",class:"status"},
388:{name:"Powder Snow",type:"ice",class:"special"},
389:{name:"Power Gem",type:"rock",class:"special"},
390:{name:"Power Split",type:"psychic",class:"status"},
391:{name:"Power Swap",type:"psychic",class:"status"},
392:{name:"Power Trick",type:"psychic",class:"status"},
393:{name:"Power Whip",type:"grass",class:"physical"},
394:{name:"Power-Up Punch",type:"fighting",class:"physical",TM:"98"},
395:{name:"Present",type:"normal",class:"physical"},
396:{name:"Protect",type:"normal",class:"status",TM:"17"},
397:{name:"Psybeam",type:"psychic",class:"special"},
398:{name:"Psych Up",type:"normal",class:"status",TM:"77"},
399:{name:"Psychic",type:"psychic",class:"special",TM:"29"},
400:{name:"Psycho Boost",type:"psychic",class:"special"},
401:{name:"Psycho Cut",type:"psychic",class:"physical"},
402:{name:"Psycho Shift",type:"psychic",class:"status"},
403:{name:"Psyshock",type:"psychic",class:"special",TM:"03"},
404:{name:"Psystrike",type:"psychic",class:"special"},
405:{name:"Psywave",type:"psychic",class:"special"},
406:{name:"Punishment",type:"dark",class:"physical"},
407:{name:"Pursuit",type:"dark",class:"physical"},
408:{name:"Quash",type:"dark",class:"status",TM:"60"},
409:{name:"Quick Attack",type:"normal",class:"physical"},
410:{name:"Quick Guard",type:"fighting",class:"status"},
411:{name:"Quiver Dance",type:"bug",class:"status"},
412:{name:"Rage",type:"normal",class:"physical"},
413:{name:"Rage Powder",type:"bug",class:"status"},
414:{name:"Rain Dance",type:"water",class:"status",TM:"18"},
415:{name:"Rapid Spin",type:"normal",class:"physical"},
416:{name:"Razor Leaf",type:"grass",class:"physical"},
417:{name:"Razor Shell",type:"water",class:"physical"},
418:{name:"Razor Wind",type:"normal",class:"special"},
419:{name:"Recover",type:"normal",class:"status"},
420:{name:"Recycle",type:"normal",class:"status"},
421:{name:"Reflect",type:"psychic",class:"status",TM:"33"},
422:{name:"Reflect Type",type:"normal",class:"status"},
423:{name:"Refresh",type:"normal",class:"status"},
424:{name:"Relic Song",type:"normal",class:"special"},
425:{name:"Rest",type:"psychic",class:"status",TM:"44"},
426:{name:"Retaliate",type:"normal",class:"physical", TM:"67"},
427:{name:"Return",type:"normal",class:"physical",TM:"27"},
428:{name:"Revenge",type:"fighting",class:"physical"},
429:{name:"Reversal",type:"fighting",class:"physical"},
430:{name:"Roar",type:"normal",class:"status",TM:"05"},
431:{name:"Roar of Time",type:"dragon",class:"special"},
432:{name:"Rock Blast",type:"rock",class:"physical"},
433:{name:"Rock Climb",type:"normal",class:"physical"},
434:{name:"Rock Polish",type:"rock",class:"status",TM:"69"},
435:{name:"Rock Slide",type:"rock",class:"physical",TM:"80"},
436:{name:"Rock Smash",type:"fighting",class:"physical",TM:"94"},
437:{name:"Rock Throw",type:"rock",class:"physical"},
438:{name:"Rock Tomb",type:"rock",class:"physical",TM:"39"},
439:{name:"Rock Wrecker",type:"rock",class:"physical"},
440:{name:"Role Play",type:"psychic",class:"status"},
441:{name:"Rolling Kick",type:"fighting",class:"physical"},
442:{name:"Rollout",type:"rock",class:"physical"},
443:{name:"Roost",type:"flying",class:"status",TM:"19"},
444:{name:"Rototiller",type:"ground",class:"status"},
445:{name:"Round",type:"normal",class:"special",TM:"48"},
446:{name:"Sacred Fire",type:"fire",class:"physical"},
447:{name:"Sacred Sword",type:"fighting",class:"physical"},
448:{name:"Safeguard",type:"normal",class:"status",TM:"20"},
449:{name:"Sand Attack",type:"ground",class:"status"},
450:{name:"Sand Tomb",type:"ground",class:"physical"},
451:{name:"Sandstorm",type:"rock",class:"status",TM:"37"},
452:{name:"Scald",type:"water",class:"special",TM:"55"},
453:{name:"Scary Face",type:"normal",class:"status"},
454:{name:"Scratch",type:"normal",class:"physical"},
455:{name:"Screech",type:"normal",class:"status"},
456:{name:"Searing Shot",type:"fire",class:"special"},
457:{name:"Secret Power",type:"normal",class:"physical"},
458:{name:"Secret Sword",type:"fighting",class:"special"},
459:{name:"Seed Bomb",type:"grass",class:"physical"},
460:{name:"Seed Flare",type:"grass",class:"special"},
461:{name:"Seismic Toss",type:"fighting",class:"physical"},
462:{name:"Self-Destruct",type:"normal",class:"physical"},
463:{name:"Shadow Ball",type:"ghost",class:"special",TM:"30"},
464:{name:"Shadow Claw",type:"ghost",class:"physical",TM:"65"},
465:{name:"Shadow Force",type:"ghost",class:"physical"},
466:{name:"Shadow Punch",type:"ghost",class:"physical"},
467:{name:"Shadow Sneak",type:"ghost",class:"physical"},
468:{name:"Sharpen",type:"normal",class:"status"},
469:{name:"Sheer Cold",type:"ice",class:"special"},
470:{name:"Shell Smash",type:"normal",class:"status"},
471:{name:"Shift Gear",type:"steel",class:"status"},
472:{name:"Shock Wave",type:"electric",class:"special"},
473:{name:"Signal Beam",type:"bug",class:"special"},
474:{name:"Silver Wind",type:"bug",class:"special"},
475:{name:"Simple Beam",type:"normal",class:"status"},
476:{name:"Sing",type:"normal",class:"status"},
477:{name:"Sketch",type:"normal",class:"status"},
478:{name:"Skill Swap",type:"psychic",class:"status"},
479:{name:"Skull Bash",type:"normal",class:"physical"},
480:{name:"Sky Attack",type:"flying",class:"physical"},
481:{name:"Sky Drop",type:"flying",class:"physical",TM:"58"},
482:{name:"Sky Uppercut",type:"fighting",class:"physical"},
483:{name:"Slack Off",type:"normal",class:"status"},
484:{name:"Slam",type:"normal",class:"physical"},
485:{name:"Slash",type:"normal",class:"physical"},
486:{name:"Sleep Powder",type:"grass",class:"status"},
487:{name:"Sleep Talk",type:"normal",class:"status",TM:"88"},
488:{name:"Sludge",type:"poison",class:"special"},
489:{name:"Sludge Bomb",type:"poison",class:"special",TM:"36"},
490:{name:"Sludge Wave",type:"poison",class:"special",TM:"34"},
491:{name:"Smack Down",type:"rock",class:"physical",TM:"23"},
492:{name:"Smelling Salts",type:"normal",class:"physical"},
493:{name:"Smog",type:"poison",class:"special"},
494:{name:"Smokescreen",type:"normal",class:"status"},
495:{name:"Snarl",type:"dark",class:"special",TM:"95"},
496:{name:"Snatch",type:"dark",class:"status"},
497:{name:"Snore",type:"normal",class:"special"},
498:{name:"Soak",type:"water",class:"status"},
499:{name:"Soft-Boiled",type:"normal",class:"status"},
500:{name:"Solar Beam",type:"grass",class:"special",TM:"22"},
501:{name:"Sonic Boom",type:"normal",class:"special"},
502:{name:"Spacial Rend",type:"dragon",class:"special"},
503:{name:"Spark",type:"electric",class:"physical"},
504:{name:"Spider Web",type:"bug",class:"status"},
505:{name:"Spike Cannon",type:"normal",class:"physical"},
506:{name:"Spikes",type:"ground",class:"status"},
507:{name:"Spiky Shield",type:"grass",class:"status"},
508:{name:"Spit Up",type:"normal",class:"special"},
509:{name:"Spite",type:"ghost",class:"status"},
510:{name:"Splash",type:"normal",class:"status"},
511:{name:"Spore",type:"grass",class:"status"},
512:{name:"Stealth Rock",type:"rock",class:"status"},
513:{name:"Steam Eruption",type:"water",class:"special"},
514:{name:"Steamroller",type:"bug",class:"physical"},
515:{name:"Steel Wing",type:"steel",class:"physical",TM:"51"},
516:{name:"Sticky Web",type:"bug",class:"status"},
517:{name:"Stockpile",type:"normal",class:"status"},
518:{name:"Stomp",type:"normal",class:"physical"},
519:{name:"Stone Edge",type:"rock",class:"physical", TM:"71"},
520:{name:"Stored Power",type:"psychic",class:"special"},
521:{name:"Storm Throw",type:"fighting",class:"physical"},
522:{name:"Strength",type:"normal",class:"physical",TM:"HM04"},
523:{name:"String Shot",type:"bug",class:"status"},
524:{name:"Struggle",type:"normal",class:"physical"},
525:{name:"Struggle Bug",type:"bug",class:"special",TM:"76"},
526:{name:"Stun Spore",type:"grass",class:"status"},
527:{name:"Submission",type:"fighting",class:"physical"},
528:{name:"Substitute",type:"normal",class:"status",TM:"90"},
529:{name:"Sucker Punch",type:"dark",class:"physical"},
530:{name:"Sunny Day",type:"fire",class:"status",TM:"11"},
531:{name:"Super Fang",type:"normal",class:"physical"},
532:{name:"Superpower",type:"fighting",class:"physical"},
533:{name:"Supersonic",type:"normal",class:"status"},
534:{name:"Surf",type:"water",class:"special",TM:"HM03"},
535:{name:"Swagger",type:"normal",class:"status",TM:"87"},
536:{name:"Swallow",type:"normal",class:"status"},
537:{name:"Sweet Kiss",type:"fairy",class:"status"},
538:{name:"Sweet Scent",type:"normal",class:"status"},
539:{name:"Swift",type:"normal",class:"special"},
540:{name:"Switcheroo",type:"dark",class:"status"},
541:{name:"Swords Dance",type:"normal",class:"status",TM:"75"},
542:{name:"Synchronoise",type:"psychic",class:"special"},
543:{name:"Synthesis",type:"grass",class:"status"},
544:{name:"Tackle",type:"normal",class:"physical"},
545:{name:"Tail Glow",type:"bug",class:"status"},
546:{name:"Tail Slap",type:"normal",class:"physical"},
547:{name:"Tail Whip",type:"normal",class:"status"},
548:{name:"Tailwind",type:"flying",class:"status"},
549:{name:"Take Down",type:"normal",class:"physical"},
550:{name:"Taunt",type:"dark",class:"status",TM:"12"},
551:{name:"Techno Blast",type:"normal",class:"special"},
552:{name:"Teeter Dance",type:"normal",class:"status"},
553:{name:"Telekinesis",type:"psychic",class:"status"},
554:{name:"Teleport",type:"psychic",class:"status"},
555:{name:"Thief",type:"dark",class:"physical",TM:"46"},
556:{name:"Thrash",type:"normal",class:"physical"},
557:{name:"Thunder",type:"electric",class:"special",TM:"25"},
558:{name:"Thunder Fang",type:"electric",class:"physical"},
559:{name:"Thunder Punch",type:"electric",class:"physical"},
560:{name:"Thunder Shock",type:"electric",class:"special"},
561:{name:"Thunder Wave",type:"electric",class:"status",TM:"73"},
562:{name:"Thunderbolt",type:"electric",class:"special",TM:"24"},
563:{name:"Tickle",type:"normal",class:"status"},
564:{name:"Topsy-Turvy",type:"dark",class:"status"},
565:{name:"Torment",type:"dark",class:"status",TM:"41"},
566:{name:"Toxic",type:"poison",class:"status",TM:"06"},
567:{name:"Toxic Spikes",type:"poison",class:"status"},
568:{name:"Transform",type:"normal",class:"status"},
569:{name:"Tri Attack",type:"normal",class:"special"},
570:{name:"Trick",type:"psychic",class:"status"},
571:{name:"Trick Room",type:"psychic",class:"status",TM:"92"},
572:{name:"Trick-or-Treat",type:"ghost",class:"status"},
573:{name:"Triple Kick",type:"fighting",class:"physical"},
574:{name:"Trump Card",type:"normal",class:"special"},
575:{name:"Twineedle",type:"bug",class:"physical"},
576:{name:"Twister",type:"dragon",class:"special"},
577:{name:"U-turn",type:"bug",class:"physical",TM:"89"},
578:{name:"Uproar",type:"normal",class:"special"},
579:{name:"V-create",type:"fire",class:"physical"},
580:{name:"Vacuum Wave",type:"fighting",class:"special"},
581:{name:"Venom Drench",type:"poison",class:"status"},
582:{name:"Venoshock",type:"poison",class:"special",TM:"09"},
583:{name:"Vice Grip",type:"normal",class:"physical"},
584:{name:"Vine Whip",type:"grass",class:"physical"},
585:{name:"Vital Throw",type:"fighting",class:"physical"},
586:{name:"Volt Switch",type:"electric",class:"special",TM:"72"},
587:{name:"Volt Tackle",type:"electric",class:"physical"},
588:{name:"Wake-Up Slap",type:"fighting",class:"physical"},
589:{name:"Water Gun",type:"water",class:"special"},
590:{name:"Water Pledge",type:"water",class:"special"},
591:{name:"Water Pulse",type:"water",class:"special"},
592:{name:"Water Shuriken",type:"water",class:"physical"},
593:{name:"Water Sport",type:"water",class:"status"},
594:{name:"Water Spout",type:"water",class:"special"},
595:{name:"Waterfall",type:"water",class:"physical",TM:"HM05"},
596:{name:"Weather Ball",type:"normal",class:"special"},
597:{name:"Whirlpool",type:"water",class:"special"},
598:{name:"Whirlwind",type:"normal",class:"status"},
599:{name:"Wide Guard",type:"rock",class:"status"},
600:{name:"Wild Charge",type:"electric",class:"physical",TM:"93"},
601:{name:"Will-O-Wisp",type:"fire",class:"status",TM:"61"},
602:{name:"Wing Attack",type:"flying",class:"physical"},
603:{name:"Wish",type:"normal",class:"status"},
604:{name:"Withdraw",type:"water",class:"status"},
605:{name:"Wonder Room",type:"psychic",class:"status"},
606:{name:"Wood Hammer",type:"grass",class:"physical"},
607:{name:"Work Up",type:"normal",class:"status"},
608:{name:"Worry Seed",type:"grass",class:"status"},
609:{name:"Wrap",type:"normal",class:"physical"},
610:{name:"Wring Out",type:"normal",class:"special"},
611:{name:"X-Scissor",type:"bug",class:"physical",TM:"81"},
612:{name:"Yawn",type:"normal",class:"status"},
613:{name:"Zap Cannon",type:"electric",class:"special"},
614:{name:"Zen Headbutt",type:"psychic",class:"physical"}
}
